/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas;

import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class user extends javax.swing.JFrame {
private final hasil hsl = new hasil();
    

    
    public user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        asal = new javax.swing.JComboBox<>();
        login = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destinasi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lanjut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Destinasi");

        asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi" }));
        asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setText("Apakah Riders punya Member Card?");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hai Riders, Sebelum jalan -jalan isi nama dulu yukk ");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Asal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Asal Kamu dari mana ?");

        destinasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi" }));
        destinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinasiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nama");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fikri muhammad\\Downloads\\Ojol-removebg-preview.png")); // NOI18N

        lanjut.setText("Konfirmasi");
        lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanjutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mau Kemana hari ini ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addComponent(jLabel7))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addComponent(destinasi, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(login)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(171, 171, 171)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(asal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(asal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(destinasi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(login)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(lanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void lanjutActionPerformed(java.awt.event.ActionEvent evt) {                                       
           String asal2,dest;
          double jarak = 0,harga = 0,total=0;
          int result ;
          JFrame frame = new JFrame(); 
          asal2 = (String) asal.getSelectedItem();
          dest = (String) destinasi.getSelectedItem();
        if(login.isSelected()){
            int i=0;
            do{
        JTextField userField = new JTextField();
        JPasswordField passField = new JPasswordField();
        String message = "Please enter your user name and password.";
        result = JOptionPane.showOptionDialog(frame, new Object[] {message, userField, passField},
        "Login", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if (result == JOptionPane.OK_OPTION){
            String username,password;
            username="alif";
            password="12345";
        
        if (username.equalsIgnoreCase(userField.getText())&& password.equalsIgnoreCase(passField.getText()))
        {
            i=1;
            String[] driver = new String[]{
            "Pak Jarmo" ,"Pak Kimin" ,"Pak Owi","Pak Darto"
                ,"Pak Kanwo" ,"Pak Ambatu" , "Pak Lawu"
        };
                Random r = new Random();
        int id = r.nextInt(driver.length);
        hsl.drivers.setText(driver[id]);
        hsl.drivers.setEditable(false);
            
            hsl.setVisible(true);
            hsl.setData1(nama);
            hsl.setData(asal);
            hsl.setData2(destinasi);
            hsl.setData3(alamat);
            
            switch(asal2){
              
              case "Jakarta":
                  switch(dest){
                      case "Bogor":
                          jarak = 56.2;
                          break;
                      case "Depok":
                          jarak = 26.7;
                          break;
                      case "Tangerang":
                          jarak = 30.1;
                          break;
                      case "Bekasi":
                          jarak = 27.9;
                          break;
                  } 
                  break;
              case "Bogor":
                  switch(dest){
                      case "Jakarta":
                          jarak = 56.2;
                          break;
                      case "Depok":
                          jarak = 44;
                          break;
                      case "Tangerang":
                          jarak = 82.1;
                          break;
                      case "Bekasi":
                          jarak = 53.4;
                          break;
                  }
                  break;
               case "Depok":
                  switch(dest){
                      case "Jakarta":
                          jarak = 26.7;
                          break;
                      case "Bogor":
                          jarak = 44;
                          break;
                      case "Tangerang":
                          jarak = 46.3;
                          break;
                      case "Bekasi":
                          jarak = 39;
                          break;
                  }
                  break;
                  case "Tangerang":
                  switch(dest){
                      case "Jakarta":
                          jarak = 30.1;
                          break;
                      case "Bogor":
                          jarak = 82.1;
                          break;
                      case "Depok":
                          jarak = 46.3;
                          break;
                      case "Bekasi":
                          jarak = 54.2;
                          break;
                  }
                  break;
                  case "Bekasi":
                  switch(dest){
                      case "Jakarta":
                          jarak = 27.9;
                          break;
                      case "Bogor":
                          jarak = 53.4;
                          break;
                      case "Tangerang":
                          jarak = 54.2;
                          break;
                      case "Depok":
                          jarak = 39;
                          break;
                          
                  }
                    
          }
            
          hsl.jar.setText(String.valueOf(jarak) +" KM");
          hsl.jar.setEditable(false);
          harga=jarak*10;
          total= harga - 50;
          hsl.har.setText("Rp "+String.valueOf(total) +"00");
          hsl.har.setEditable(false);
        }
            
         else{
            JOptionPane.showMessageDialog(null, "Maaf username dan password salah");
            
        }   
        }
        else{
        i=1;
        }
        }while(i==0);
            
      }else{

          switch(asal2){
              
              case "Jakarta":
                  switch(dest){
                      case "Bogor":
                          jarak = 56.2;
                          break;
                      case "Depok":
                          jarak = 26.7;
                          break;
                      case "Tangerang":
                          jarak = 30.1;
                          break;
                      case "Bekasi":
                          jarak = 27.9;
                          break;
                  } 
                  break;
              case "Bogor":
                  switch(dest){
                      case "Jakarta":
                          jarak = 56.2;
                          break;
                      case "Depok":
                          jarak = 44;
                          break;
                      case "Tangerang":
                          jarak = 82.1;
                          break;
                      case "Bekasi":
                          jarak = 53.4;
                          break;
                  }
                  break;
               case "Depok":
                  switch(dest){
                      case "Jakarta":
                          jarak = 26.7;
                          break;
                      case "Bogor":
                          jarak = 44;
                          break;
                      case "Tangerang":
                          jarak = 46.3;
                          break;
                      case "Bekasi":
                          jarak = 39;
                          break;
                  }
                  break;
                  case "Tangerang":
                  switch(dest){
                      case "Jakarta":
                          jarak = 30.1;
                          break;
                      case "Bogor":
                          jarak = 82.1;
                          break;
                      case "Depok":
                          jarak = 46.3;
                          break;
                      case "Bekasi":
                          jarak = 54.2;
                          break;
                  }
                  break;
                  case "Bekasi":
                  switch(dest){
                      case "Jakarta":
                          jarak = 27.9;
                         // harga = 279;
                          break;
                      case "Bogor":
                          jarak = 53.4;
                          break;
                      case "Tangerang":
                          jarak = 54.2;
                          break;
                      case "Depok":
                          jarak = 39;
                          break;
                          
                  }
                    
          }
          
          hsl.jar.setText(String.valueOf(jarak) +" KM");
          hsl.jar.setEditable(false);
          harga=jarak*10;
          hsl.har.setText("Rp "+String.valueOf(harga) +"00");
          hsl.har.setEditable(false);
          
        String[] driver = new String[]{
        "Pak Jarmo" ,"Pak Kimin" ,"Pak Owi","Pak Darto"
                ,"Pak Kanwo" ,"Pak Ambatu" , "Pak Lawu"
        };
        
        Random r = new Random();
        int id = r.nextInt(driver.length);
        hsl.drivers.setText(driver[id]);
        hsl.drivers.setEditable(false);
        
         hsl.setVisible(true);
         hsl.setData1(nama);
         hsl.setData(asal);
         hsl.setData2(destinasi);
         hsl.setData3(alamat);
         
         
      }
     
    }                                      

    private void destinasiActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void asalActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField alamat;
    public javax.swing.JComboBox<String> asal;
    public javax.swing.JComboBox<String> destinasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lanjut;
    private javax.swing.JCheckBox login;
    public javax.swing.JTextField nama;
    // End of variables declaration                   
}
